name: GitHub Pages
on:
    push:
        branches:
            - "main"
        paths:
            - "public/**"
            - "src/**"
            - "package.json"
            - "package-lock.json"
    pull_request:
        branches:
            - "main"
    workflow_dispatch:

defaults:
    run:
        working-directory: /documents

jobs:
    build-website:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              run: |
                  # Set repository Url
                  REPOSITORY_URL="${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}.git"
                  BRANCH_NAME="${GITHUB_REF#refs/heads/}"

                  # Clone repository
                  git clone --depth 2 -b "${BRANCH_NAME}" --no-single-branch "${REPOSITORY_URL}" .

                  # Don't switch to gh-pages if not on main
                  if [ "${BRANCH_NAME}" == "main" ]; then
                      # Switch to gh-pages branch
                      if ! git show-branch remotes/origin/gh-pages; then
                          # If the branch doesn't exist, then create an orphan branch
                          echo "Could not find gh-pages branch, creating as orphan"
                          git switch --orphan gh-pages
                      else
                          # Else, switch to the branch
                          echo "Creating gh-pages branch as an orphan branch"
                          git switch gh-pages
                      fi
                      
                      # Delete all old files
                      rm -rf *

                      # Get latest source and buildscript
                      git restore -s "${BRANCH_NAME}" public src package.json package-lock.json
                  fi
            - name: Build site using Create React App
              run: |
                  # Build page
                  sudo apt update
                  sudo apt install nodejs
                  sudo apt install npm
                  sudo apt install npx
                  npx create-react-app preview-markdown
                  cp -Tv public/ preview-markdown/public
                  cp -Tv src/ preview-markdown/src
                  cp -Tv package.json preview-markdown/package.json
                  cp -Tv package-lock.json preview-markdown/package-lock.json
                  rm -rf public src package.json package-lock.json
                  cd preview-markdown
                  npm install
                  npm run build
                  cd build
                  mv * ../../
                  cd ../..
                  rm -rf preview-markdown

            - name: Deploy to GitHub Pages
              run: |
                  # Skip deploy if not on main
                  BRANCH_NAME="${GITHUB_REF#refs/heads/}"
                  if [ "${BRANCH_NAME}" != "main" ]; then
                    echo "Skipping deployment since branch is '${BRANCH_NAME}', not main"
                    exit 0
                  fi

                  # Add modified files
                  git add .

                  # Set user
                  git config user.name  "Auto deploy GitHub Pages"
                  git config user.email "cd-deploy-gh-pages@bot"

                  # Commit changes
                  git commit -m "Deploy to pages: $(date +'%Y-%m-%d %T')"

                  # Remove 'https://' from beginning of REPOSITORY_URL
                  REPOSITORY_URL="${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}.git"
                  git push "https://X-Access-Token:${{ secrets.GITHUB_TOKEN }}@${REPOSITORY_URL:8}" gh-pages
